# Generated by Django 2.2.15 on 2020-08-16 14:56

from django.db import migrations, models
import statetrace_django.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Annotation",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("id", models.TextField()),
                ("kind", models.TextField()),
                ("meta", statetrace_django.models.JSONField(null=True)),
                ("payload", statetrace_django.models.JSONField(null=True))
            ],
            options={
                "db_table": "statetrace_annotations",
            },
        ),
    ]
